### ISSUE TITLE
Node sqlite3 dependency only distributed for macOS/Darwin platforms

### ISSUE THREAD

**Issue by aj-stein-nist** [transmute-industries/transmute#249]
I will investigate and examine how I can contribute a fix back when I review more, but in the context of evaluating scitt-community/scitt-examples#2, I am unable to build this in a current version of Ubuntu Linux 22.04 for the amd64 ISA because the necessary sqlite3 dependency requires compiled bindings that are platform specific. The only provided binding is Darwin/macOS.

Given the platform below,

```sh
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
$ node --version
v16.19.0
$ npm --version
8.19.3
```

I received the following error.

```sh
$ npm ci 
$ $(npm bin)/transmute
node:internal/modules/cjs/loader:1249
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: /home/me/code/scitt-examples/nodejs/node_modules/@transmute/cli/dist/lib/binding/napi-v6-darwin-unknown-arm64/node_sqlite3.node: invalid ELF header
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1249:18)
    at Module.load (node:internal/modules/cjs/loader:1043:32)
    at Function.Module._load (node:internal/modules/cjs/loader:878:12)
    at Module.require (node:internal/modules/cjs/loader:1067:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.53751 (/home/me/code/scitt-examples/nodejs/node_modules/@transmute/cli/dist/index.js:245:113933)
    at __nccwpck_require__ (/home/me/code/scitt-examples/nodejs/node_modules/@transmute/cli/dist/index.js:254:456010)
    at Object.80729 (/home/me/code/scitt-examples/nodejs/node_modules/@transmute/cli/dist/index.js:226:5388)
    at __nccwpck_require__ (/home/me/code/scitt-examples/nodejs/node_modules/@transmute/cli/dist/index.js:254:456010)
    at Object.54946 (/home/me/code/scitt-examples/nodejs/node_modules/@transmute/cli/dist/index.js:226:5463) {
  code: 'ERR_DLOPEN_FAILED'
}
```

Note: I currently do not have a macOS system to test, but I will try to determine a recommended fix as I confirm it is macOS-specific.

**Comment by OR13** [comment]
I dropped the sqlite ledger for now, the latest version just uses a json file.

```
npm i -g @transmute/cli@0.8.30
```
